apiVersion: v2
name: tz-mcall-crd
description: A Helm chart for mcall CRD-based task execution system
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/doohee323/tz-mcall-crd
sources:
  - https://github.com/doohee323/tz-mcall-crd
maintainers:
  - name: Dewey Hong
    email: doohee323@gmail.com
keywords:
  - mcall
  - task-execution
  - crd
  - kubernetes
  - workflow
annotations:
  category: Infrastructure
  licenses: MIT


