{{- if .Values.service.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcall-crd.metricsServiceName" . }}
  namespace: {{ include "mcall-crd.namespace" . }}
  labels:
    {{- include "mcall-crd.labels" . | nindent 4 }}
  {{- with .Values.service.metrics.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.metrics.type }}
  ports:
  - port: {{ .Values.service.metrics.port }}
    targetPort: {{ .Values.service.metrics.targetPort }}
    protocol: TCP
    name: metrics
  selector:
    {{- include "mcall-crd.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.service.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcall-crd.webhookServiceName" . }}
  namespace: {{ include "mcall-crd.namespace" . }}
  labels:
    {{- include "mcall-crd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.webhook.type }}
  ports:
  - port: {{ .Values.service.webhook.port }}
    targetPort: {{ .Values.service.webhook.targetPort }}
    protocol: TCP
    name: webhook
  selector:
    {{- include "mcall-crd.selectorLabels" . | nindent 4 }}
{{- end }}


